adminapp/urls.py
from django.conf.urls import url
from django.urls import include, path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),
    
    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'), 
]

authapp/urls.py
from django.conf.urls import url
from django.urls import include, path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]
    

    

basketapp/urls.py
from django.conf.urls import url
from django.urls import include, path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path(r'', basketapp.basket, name='view'),
    path(r'add/<int:pk>/', basketapp.basket_add, name='add'),
    path(r'remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    
    path(r'edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

    

geekshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import mainapp.views as mainapp
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/verify/google/oauth2/', include("social_django.urls", namespace="social"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url
from django.urls import include, path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),

]

    

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$',
            ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(),
            name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(),
            name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(),
            name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(),
            name='order_delete'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='категория активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='категория активна', default=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
import datetime, random, os, json
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

JSON_PATH = 'mainapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r') as infile:
        return json.load(infile)


def get_hot_product():
    products = Product.objects.filter(is_active=True, category__is_active=True)

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    title = 'главная'
    products = Product.objects.filter(is_active=True, category__is_active=True)[:3]

    content = {
        'title': title,
        'products': products,
    }

    return render(request, 'mainapp/index.html', content)


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk:
        if pk == '0':
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)

    product = get_object_or_404(Product, pk=pk)

    content = {
        'title': title,
        'links_menu': links_menu,
        'product': product,
    }
    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = 'о нас'

    locations = load_from_json('contact__locations')

    content = {
        'title': title,
        'locations': locations,
    }

    return render(request, 'mainapp/contact.html', content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.kwargs.pk == '0' %}active{% endif %}">
            все
        </a>
    </li>
    {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}" class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}active{% endif %}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}" class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    {% endif %}
    {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin:users' %}">админка</a>
        </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket %} 
            {{ basket.0.get_total_cost|floatformat:0 }} руб ({{ basket.0.get_total_quantity }} шт)
        {% endif %}
    </span>
</a>