authapp/urls.py
from django.conf.urls import url
from django.urls import include, path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]
    

    

basketapp/urls.py
from django.conf.urls import url
from django.urls import include, path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path(r'', basketapp.basket, name='view'),
    path(r'add/<int:pk>/', basketapp.basket_add, name='add'),
    path(r'remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    
    path(r'edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

    

geekshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import mainapp.views as mainapp
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/verify/google/oauth2/', include("social_django.urls", namespace="social"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url
from django.urls import include, path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),

]

    

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='категория активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='категория активна', default=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
import datetime, random, os, json
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

JSON_PATH = 'mainapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r') as infile:
        return json.load(infile)


def get_hot_product():
    products = Product.objects.filter(is_active=True, category__is_active=True)

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    title = 'главная'
    products = Product.objects.filter(is_active=True, category__is_active=True)[:3]

    content = {
        'title': title,
        'products': products,
    }

    return render(request, 'mainapp/index.html', content)


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk:
        if pk == '0':
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)

    product = get_object_or_404(Product, pk=pk)

    content = {
        'title': title,
        'links_menu': links_menu,
        'product': product,
    }
    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = 'о нас'

    locations = load_from_json('contact__locations')

    content = {
        'title': title,
        'locations': locations,
    }

    return render(request, 'mainapp/contact.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|capfirst }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="container">
		{% block menu %}
			<div class="hero-white">
				<div class="header clearfix">
					{% include 'mainapp/includes/inc_menu.html' %}
				</div>
			</div>
        {% endblock %}
        <div class="content">
        {% block content %}

        {% endblock %}
        </div>

	</div>
    
    {% block footer %}
        <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
            <p class="small">&copy; GB {% now "Y" %}</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}
	
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}   
    <div class="hero">
		<div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
		</div>
		<h1>наши контакты</h1>
	</div>
{% endblock %}

{% block content %}
    <div class="location">
        {% for location in locations %}
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>{{ location.city }}</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>{{ location.phone }}</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>{{ location.email }}</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>{{ location.address }}</p>
            </div>
        </div>
       {% endfor %}
    </div>

    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
    <div class="slider">
        <div class="header clearfix">
                {% include 'mainapp/includes/inc_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="{% url 'products:index' %}" class="button-order">
                заказать
                <img src="{% static 'img/arrow.png' %}" alt="">
            </a>
        </div>	
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}


{% block content %}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:product' product.pk %}">
                        <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}"> 
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h3>Категория:{{ product.category.name }}</h3>
                            <h4>Название: {{ product.name }}</h4>
                            <p>Описание: {{ product.description }} </p>
                            <p>Цена: {{ product.price }} </p>
                            <p>На складе: {{ product.quantity }} </p>
                        </div> 
                    </a>
                </div>
            {% endfor %}	
        </div>
    </div>
    
    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 1">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 2">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 3">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать 
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ hot_product.description }} 
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h3>Категория:{{ product.category.name }}</h3>
                                <h4>Название: {{ product.name }}</h4>
                                <p>Описание: {{ product.description }} </p>
                                <p>Цена: {{ product.price }} </p>
                                <p>На складе: {{ product.quantity }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>Категория: "{{ category.name|title }}"</h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:page' category.pk products.previous_page_number %}"><</a>
                    {% endif %}
                    <span class="current">
                    страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">></a>
                    {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}