authapp/urls.py
from django.conf.urls import url
from django.urls import include, path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]
    

    

geekshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import mainapp.views as mainapp
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/verify/google/oauth2/', include("social_django.urls", namespace="social"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$',
            ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(),
            name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(),
            name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(),
            name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(),
            name='order_delete'),
]

ordersapp/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models

from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # переопределяем метод, удаляющий объект
    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name="orderitems",
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem

from mainapp.models import Product


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['product'].queryset = Product.get_items()

ordersapp/views.py
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.dispatch import receiver
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.views.generic.detail import DetailView
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.forms import inlineformset_factory

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm

from django.http import JsonResponse
from mainapp.models import Product


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.get_items(self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title>
       {% block title %}
           {{ title|title }}
       {% endblock %}
   </title>
   {% block css %}
       <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
       <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
   {% endblock %}
   {% block js %}
       <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	   <script src="{% static 'js/jquery.formset.js' %}"></script>
       <script src="{% static 'js/orders_scripts.js' %}"></script>
   {% endblock %}
</head>
<body>
  <div class="order_container">
       {% block content %}

       {% endblock %}
      
  </div>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img src="{{ item.product.image|media_folder_products }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
						   <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
							   {% if forloop.first %}
								   {% for hidden in form.hidden_fields %}
									   {{ hidden }}
								   {% endfor %}
							   {% endif %}
							   {{ field.errors.as_ul }}
							   {% if field.name != 'price' %}
								   {{ field }}
							   {% else %}
								   {% if field.value %}
									   <span class="orderitems-{{forloop.parentloop.counter0}}-price">
										 {{ field.value }}
									   </span> руб
								   {% endif %}
							   {% endif %}
						   </td>
						{% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {{ field }}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'ordersapp/includes/inc_order_actions.html' %}
       </form>
   </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}


{% block content %}
   <div class="h2 text-center head">
       Ваши заказы, 
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'main' %}">
           на главную
       </a>
   </button>
   <button class="btn btn-default btn-round">
       <a href="{% url 'ordersapp:order_create' %}">
           новый
       </a>
   </button>
{% endblock %}